    - name: Configure CMake
      run: |
        mkdir build
        cd build
        # Adicionamos flags para ignorar avisos de segurança do Windows (_CRT_SECURE_NO_WARNINGS)
        # e desativar o tratamento de avisos como erros (/WX-)
        cmake .. `
          -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DVCPKG_TARGET_TRIPLET=x64-windows `
          -DCMAKE_POLICY_DEFAULT_CMP0057=NEW `
          -DCHIAKI_ENABLE_CLI=ON `
          -DCHIAKI_ENABLE_GUI=ON `
          -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /W3 /GR /EHsc /D_CRT_SECURE_NO_WARNINGS /WX-" `
          -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3 /D_CRT_SECURE_NO_WARNINGS /WX-" `
          -Wno-dev
          
