name: Construir Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Versão estável com distutils integrado

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install protobuf==3.20.* setuptools

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'latest'

    - name: Install Dependencies (vcpkg)
      run: |
        vcpkg install sdl2 opus openssl ffmpeg --triplet x64-windows

    - name: Configure CMake
      # O uso do Ninja e compilação paralela acelera o processo
      run: |
        cmake -S . -B build `
          -G "Ninja" `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
          -D_CRT_SECURE_NO_WARNINGS=ON

    - name: Build
      run: |
        cmake --build build --config Release --parallel 4

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: chiaki-windows
        path: build/gui/chiaki.exe
